"https://www.{default}/":
    type: upstream
    upstream: "gatsby:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://backend.{default}/":
    type: upstream
    upstream: "drupal:http"
    cache:
      enabled: true
      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies:
          - '/^Drupal.visitor/'
          - '/^SS?ESS/'
          - '/^comment_/'
          - '/^wordpress_/'
          - '/^wordpress_logged_in_/'
          - '/^wordpress_sec_/'
          - 'wordpress_test_cookie'
          - '/^wp-settings-/'
          - '/^wp-resetpass-/'
          - '/^wp-postpass/'

"https://www.backend.{default}/":
    type: redirect
    to: "https://backend.{default}/"
