"https://api.{default}/":
    type: upstream
    upstream: "drupal:http"
    cache:
      enabled: true
      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://www.api.{default}/":
    type: redirect
    to: "https://api.{default}/"

# "https://www.{default}/":
#     type: upstream
#     upstream: "gatsby:http"

# "https://{default}/":
#     type: redirect
#     to: "https://www.{default}/"
