# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

dbb:
    type: mariadb:10.4
    disk: 2048

cacheb:
    type: redis:5.0

filesb:
  type: network-storage:1.0
  disk: 256
